### ISSUE TITLE
"undefined reference to qi" errors

### ISSUE THREAD

**Issue by Ruthrash** [LCAS/spqrel_navigation#10]
Hey, 

I tried using the naoqi 2.5.5 as well as 2.5.7 C++ sdk to compile SPQREL_navigation but when compiling "/pepper_localizer.dir/pepper_localizer.cpp" I am getting a bunch of "undefined reference errors" (eg. undefined reference to `qi::TypeInfo::operator<(qi::TypeInfo const&) const' undefined reference to `qi::SignalSubscriber::~SignalSubscriber()') However I see that these objects are defined in the naoqi 2.5 in the documentation. I would be very grateful if you can give any directions in solving this error.

thanks

**Comment by MFernandezCarmona** [comment]
Hi,
Did you followed the instructions at https://github.com/LCAS/spqrel_navigation/wiki/NAOQI-Installation-and-Usage ?

**Comment by Ruthrash** [comment]
Thanks for getting back to me. I was able to solve the problem. I had not installed the c++ SDK properly and it had nothing to do with the SPQREL's package. 

Cheers,
Ruthrash Hari
