### ISSUE TITLE
std::logic_error

### ISSUE THREAD

**Issue by ghost** [LCAS/spqrel_navigation#6]
Hello Sir, When I tried to run pepper planner it produces this error however the localizer is running well.

I am using UBUNTU 14.04

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

**Comment by mtlazaro** [comment]
Dear @hkhaledmohamed,
could you check if you have set up properly the PEPPER_IP environment variable?

Check installation and set-up instructions here:
https://github.com/LCAS/spqrel_navigation/wiki/NAOQI-Installation-and-Usage

Let us know if the error persists.

**Comment by ghost** [comment]
Yes Thanks so much
